stages:
  download_data:
    cmd: Rscript R/build.R
    deps:
    - R/build.R
    outs:
      - data/TCGA-ACC/clinical_patient_acc.parquet
      - data/TCGA-BLCA/clinical_patient_blca.parquet
      - data/TCGA-BRCA/clinical_patient_brca.parquet
      - data/TCGA-CESC/clinical_patient_cesc.parquet
      - data/TCGA-CHOL/clinical_patient_chol.parquet
      - data/TCGA-COAD/clinical_patient_coad.parquet
      - data/TCGA-DLBC/clinical_patient_dlbc.parquet
      - data/TCGA-ESCA/clinical_patient_esca.parquet
      - data/TCGA-GBM/clinical_patient_gbm.parquet
      - data/TCGA-HNSC/clinical_patient_hnsc.parquet
      - data/TCGA-KICH/clinical_patient_kich.parquet
      - data/TCGA-KIRC/clinical_patient_kirc.parquet
      - data/TCGA-KIRP/clinical_patient_kirp.parquet
      - data/TCGA-LAML/clinical_patient_laml.parquet
      - data/TCGA-LGG/clinical_patient_lgg.parquet
      - data/TCGA-LIHC/clinical_patient_lihc.parquet
      - data/TCGA-LUAD/clinical_patient_luad.parquet
      - data/TCGA-LUSC/clinical_patient_lusc.parquet
      - data/TCGA-MESO/clinical_patient_meso.parquet
      - data/TCGA-OV/clinical_patient_ov.parquet
      - data/TCGA-PAAD/clinical_patient_paad.parquet
      - data/TCGA-PCPG/clinical_patient_pcpg.parquet
      - data/TCGA-PRAD/clinical_patient_prad.parquet
      - data/TCGA-READ/clinical_patient_read.parquet
      - data/TCGA-SARC/clinical_patient_sarc.parquet
      - data/TCGA-SKCM/clinical_patient_skcm.parquet
      - data/TCGA-STAD/clinical_patient_stad.parquet
      - data/TCGA-TGCT/clinical_patient_tgct.parquet
      - data/TCGA-THCA/clinical_patient_thca.parquet
      - data/TCGA-THYM/clinical_patient_thym.parquet
      - data/TCGA-UCEC/clinical_patient_ucec.parquet
      - data/TCGA-UCS/clinical_patient_ucs.parquet
      - data/TCGA-UVM/clinical_patient_uvm.parquet
      - data/TCGA-ACC/clinical_drug_acc.parquet
      - data/TCGA-BLCA/clinical_drug_blca.parquet
      - data/TCGA-BRCA/clinical_drug_brca.parquet
      - data/TCGA-CESC/clinical_drug_cesc.parquet
      - data/TCGA-CHOL/clinical_drug_chol.parquet
      - data/TCGA-COAD/clinical_drug_coad.parquet
      - data/TCGA-DLBC/clinical_drug_dlbc.parquet
      - data/TCGA-ESCA/clinical_drug_esca.parquet
      - data/TCGA-GBM/clinical_drug_gbm.parquet
      - data/TCGA-HNSC/clinical_drug_hnsc.parquet
      - data/TCGA-KICH/clinical_drug_kich.parquet
      - data/TCGA-KIRC/clinical_drug_kirc.parquet
      - data/TCGA-KIRP/clinical_drug_kirp.parquet
      - data/TCGA-LGG/clinical_drug_lgg.parquet
      - data/TCGA-LIHC/clinical_drug_lihc.parquet
      - data/TCGA-LUAD/clinical_drug_luad.parquet
      - data/TCGA-LUSC/clinical_drug_lusc.parquet
      - data/TCGA-MESO/clinical_drug_meso.parquet
      - data/TCGA-OV/clinical_drug_ov.parquet
      - data/TCGA-PAAD/clinical_drug_paad.parquet
      - data/TCGA-PCPG/clinical_drug_pcpg.parquet
      - data/TCGA-PRAD/clinical_drug_prad.parquet
      - data/TCGA-READ/clinical_drug_read.parquet
      - data/TCGA-SARC/clinical_drug_sarc.parquet
      - data/TCGA-SKCM/clinical_drug_skcm.parquet
      - data/TCGA-STAD/clinical_drug_stad.parquet
      - data/TCGA-TGCT/clinical_drug_tgct.parquet
      - data/TCGA-THCA/clinical_drug_thca.parquet
      - data/TCGA-THYM/clinical_drug_thym.parquet
      - data/TCGA-UCEC/clinical_drug_ucec.parquet
      - data/TCGA-UCS/clinical_drug_ucs.parquet
      - data/TCGA-UVM/clinical_drug_uvm.parquet
      - data/TCGA-ACC/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-BLCA/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-BRCA/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-CESC/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-CHOL/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-COAD/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-DLBC/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-ESCA/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-GBM/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-HNSC/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-KICH/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-KIRC/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-KIRP/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-LAML/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-LGG/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-LIHC/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-LUAD/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-LUSC/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-MESO/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-OV/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-PCPG/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-PRAD/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-READ/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-SARC/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-STAD/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-TGCT/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-THCA/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-THYM/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-UCEC/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-UCS/wxs.aliquot_ensemble_masked.maf.parquet
      - data/TCGA-UVM/wxs.aliquot_ensemble_masked.maf.parquet
      - data/combined.wxs.aliquot_ensemble_masked.maf.parquet
      - data/combined_clinical_drug.parquet
      - data/combined_clinical_patient.parquet
  add_cases:
    cmd: Rscript R/add_cases.R
    deps: 
    - R/add_cases.R
    - data/combined.wxs.aliquot_ensemble_masked.maf.parquet
    outs:
    - data/gdc2tcga.parquet
